import { BookOpenCheck, GraduationCap, Plus, Users, X } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { EmptyState } from '../../ui/EmptyState';
import { ErrorState } from '../../ui/ErrorState';
import { MetricCard } from '../../ui/MetricCard';
import { PageHeader } from '../../ui/PageHeader';
import { MetricSkeletonRow } from '../../ui/Skeletons';
import { StatusBadge } from '../../ui/StatusBadge';
import { useLearningAdminCatalog, useLearningCommands } from './useEnterpriseOperations';

export function LearningPage() {
  const query = useLearningAdminCatalog(); const commands = useLearningCommands();
  const [showCourse, setShowCourse] = useState(false); const [showEnrollment, setShowEnrollment] = useState(false);
  const [course, setCourse] = useState({ code: '', title: '', category: 'عام', deliveryMode: 'online', durationMinutes: 60, mandatory: false, active: true });
  const [enrollment, setEnrollment] = useState({ employeeId: '', courseId: '' });
  const data = query.data;
  async function saveCourse(e: FormEvent) { e.preventDefault(); await commands.upsertCourse.mutateAsync(course); setShowCourse(false); setCourse({ code: '', title: '', category: 'عام', deliveryMode: 'online', durationMinutes: 60, mandatory: false, active: true }); }
  async function saveEnrollment(e: FormEvent) { e.preventDefault(); await commands.enroll.mutateAsync(enrollment); setShowEnrollment(false); }
  if (query.isError) return <ErrorState title="تعذر تحميل التدريب" description={query.error instanceof Error ? query.error.message : undefined} onRetry={() => void query.refetch()} />;
  return <div className="space-y-6">
    <PageHeader title="التدريب والمهارات" description="كتالوج الدورات، التسجيل، الإكمال، الشهادات ومتابعة الدورات الإلزامية." actions={<div className="flex gap-2"><button className="btn-secondary" onClick={() => setShowEnrollment(true)}><Users className="size-4" />تسجيل موظف</button><button className="btn-primary" onClick={() => setShowCourse(true)}><Plus className="size-4" />دورة جديدة</button></div>} />
    {query.isLoading && !data ? <MetricSkeletonRow count={3} /> : null}
    {data ? <>
      <section className="grid gap-4 sm:grid-cols-3"><MetricCard label="الدورات" value={data.courses.length} icon={GraduationCap} /><MetricCard label="التسجيلات" value={data.enrollments.length} icon={Users} /><MetricCard label="المكتملة" value={data.enrollments.filter(x => x.status === 'completed').length} icon={BookOpenCheck} /></section>
      <section className="grid gap-5 xl:grid-cols-[1fr_1.4fr]">
        <article className="card overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="font-black">الدورات</h2></div><div className="divide-y divide-[var(--border)]">{data.courses.length ? data.courses.map(c => <div className="p-5" key={c.id}><div className="flex justify-between gap-3"><div><p className="font-black">{c.title}</p><p className="muted text-sm">{c.code} · {c.category} · {c.durationMinutes} دقيقة</p></div><StatusBadge value={c.active ? 'active' : 'inactive'} /></div><p className="muted mt-2 text-sm">المسجلون {c.enrollments} · المكتمل {c.completed}{c.mandatory ? ' · إلزامية' : ''}</p></div>) : <EmptyState title="لا توجد دورات" description="أنشئ أول دورة تدريبية." />}</div></article>
        <article className="card overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="font-black">تسجيلات الموظفين</h2></div><div className="divide-y divide-[var(--border)]">{data.enrollments.length ? data.enrollments.map(x => <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={x.id}><div><p className="font-black">{x.employeeName}</p><p className="muted text-sm">{x.courseTitle} · تقدم {x.progress}%</p></div><div className="flex items-center gap-2"><StatusBadge value={x.status} />{x.status !== 'completed' ? <button className="btn-secondary" onClick={() => commands.transition.mutate({ enrollmentId: x.id, status: 'completed' })}>إكمال</button> : null}</div></div>) : <EmptyState title="لا توجد تسجيلات" description="سجل موظفًا في دورة." />}</div></article>
      </section>
    </> : null}
    {showCourse ? <Modal title="دورة جديدة" close={() => setShowCourse(false)}><form className="space-y-4" onSubmit={saveCourse}><Field label="الكود"><input className="input" required value={course.code} onChange={e => setCourse({ ...course, code: e.target.value })} /></Field><Field label="اسم الدورة"><input className="input" required value={course.title} onChange={e => setCourse({ ...course, title: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="التصنيف"><input className="input" value={course.category} onChange={e => setCourse({ ...course, category: e.target.value })} /></Field><Field label="طريقة التقديم"><select className="input" value={course.deliveryMode} onChange={e => setCourse({ ...course, deliveryMode: e.target.value })}><option value="online">عن بعد</option><option value="onsite">حضوري</option><option value="hybrid">هجين</option><option value="self_paced">ذاتي</option></select></Field></div><Field label="المدة بالدقائق"><input className="input" type="number" min={0} value={course.durationMinutes} onChange={e => setCourse({ ...course, durationMinutes: Number(e.target.value) })} /></Field><label className="flex items-center gap-2"><input type="checkbox" checked={course.mandatory} onChange={e => setCourse({ ...course, mandatory: e.target.checked })} />دورة إلزامية</label><button className="btn-primary" disabled={commands.upsertCourse.isPending}>{commands.upsertCourse.isPending ? 'جارٍ الحفظ…' : 'حفظ'}</button></form></Modal> : null}
    {showEnrollment && data ? <Modal title="تسجيل موظف" close={() => setShowEnrollment(false)}><form className="space-y-4" onSubmit={saveEnrollment}><Field label="الموظف"><select className="input" required value={enrollment.employeeId} onChange={e => setEnrollment({ ...enrollment, employeeId: e.target.value })}><option value="">اختر…</option>{data.employees.map(e => <option key={e.id} value={e.id}>{e.name} — {e.code}</option>)}</select></Field><Field label="الدورة"><select className="input" required value={enrollment.courseId} onChange={e => setEnrollment({ ...enrollment, courseId: e.target.value })}><option value="">اختر…</option>{data.courses.filter(c => c.active).map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><button className="btn-primary" disabled={commands.enroll.isPending}>{commands.enroll.isPending ? 'جارٍ التسجيل…' : 'تسجيل'}</button></form></Modal> : null}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-bold">{label}</span>{children}</label>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="dialog-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="card max-h-[94vh] w-full max-w-2xl overflow-y-auto p-6" role="dialog" aria-modal="true" aria-labelledby="learning-modal-title"><div className="mb-5 flex items-start justify-between gap-4"><h2 id="learning-modal-title" className="text-xl font-black">{title}</h2><button type="button" className="icon-button" onClick={close} aria-label="إغلاق"><X className="size-5" /></button></div>{children}</section></div>; }
