import { Banknote, ChartNoAxesCombined, HandCoins, HeartHandshake, UsersRound } from 'lucide-react';
import { Children } from 'react';
import { EmptyState } from '../../ui/EmptyState';
import { ErrorState } from '../../ui/ErrorState';
import { MetricCard } from '../../ui/MetricCard';
import { MetricSkeletonRow, ListSkeleton } from '../../ui/Skeletons';
import { PageHeader } from '../../ui/PageHeader';
import { StatusBadge } from '../../ui/StatusBadge';
import { usePeopleFinanceCatalog } from './useEnterpriseManagement';
export function PeopleFinancePage(){const q=usePeopleFinanceCatalog();const d=q.data;return <div className="space-y-6"><PageHeader eyebrow="الإدارة" title="القوى العاملة والتعويضات" description="تخطيط العدد والطاقة، هياكل الرواتب، مسيرات الرواتب، السلف وحملات المشاركة. وحدة الرواتب تبقى Feature-gated حتى اعتماد Finance/Legal."/>{q.isError?<ErrorState description={q.error instanceof Error?q.error.message:undefined} onRetry={()=>void q.refetch()}/>:d?<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="خطط القوى العاملة" value={d.workforcePlans.length} icon={UsersRound}/><MetricCard label="هياكل الرواتب" value={d.salaryStructures.length} icon={Banknote}/><MetricCard label="مسيرات الرواتب" value={d.payrollRuns.length} icon={ChartNoAxesCombined}/><MetricCard label="السلف والقروض" value={d.loans.length} icon={HandCoins}/><MetricCard label="حملات المشاركة" value={d.campaigns.length} icon={HeartHandshake}/></section><section className="grid gap-5 xl:grid-cols-2"><Panel title="خطة القوى العاملة">{d.workforcePlans.map(x=><Row key={x.id} title={`${x.departmentName} — ${x.year}`} subtitle={`معتمد ${x.approvedHeadcount} · تعيينات ${x.plannedHires}`} status={x.status}/>)}</Panel><Panel title="الطاقة التشغيلية">{d.capacity.map(x=><Row key={x.id} title={`${x.departmentName} — ${x.snapshotDate}`} subtitle={`استغلال ${x.utilizationPercent??0}% · طلب ${x.demandMinutes} دقيقة`} status={(x.utilizationPercent??0)>100?'critical':'active'}/>)}</Panel><Panel title="مسيرات الرواتب">{d.payrollRuns.map(x=><Row key={x.id} title={`${x.periodMonth} · ${x.currency}`} subtitle={`الحالة ${x.status}`} status={x.status}/>)}</Panel><Panel title="حملات المشاركة">{d.campaigns.map(x=><Row key={x.id} title={x.title} subtitle={x.campaignType} status={x.status}/>)}</Panel><Panel title="السلف والقروض">{d.loans.map(x=><Row key={x.id} title={x.employeeName} subtitle={`${x.loanType} · متبقي ${x.outstandingAmount}`} status={x.status}/>)}</Panel></section></>:<><MetricSkeletonRow count={5}/><ListSkeleton rows={4} label="جارٍ تحميل القوى العاملة والمالية…"/></>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className="card overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="text-base font-black text-[var(--text-primary)]">{title}</h2></div><div className="divide-y divide-[var(--border)]">{Children.count(children)?children:<EmptyState title="لا توجد بيانات" description="ابدأ بإعداد الوحدة عند تفعيلها."/>}</div></article>}
function Row({title,subtitle,status}:{title:string;subtitle:string;status:string}){return <div className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{title}</p><p className="muted text-sm">{subtitle}</p></div><StatusBadge value={status}/></div>}
