import { AlertTriangle, CircleCheck, CircleMinus, CircleX, Clock3, FileText, Megaphone } from 'lucide-react';

type Tone = 'neutral' | 'info' | 'success' | 'warning' | 'danger' | 'violet';
const map: Record<string, { label: string; tone: Tone; icon: typeof CircleCheck }> = {
  draft: { label: 'مسودة', tone: 'neutral', icon: CircleMinus },
  invited: { label: 'نشط', tone: 'success', icon: CircleCheck },
  onboarding: { label: 'تهيئة', tone: 'violet', icon: Clock3 },
  active: { label: 'نشط', tone: 'success', icon: CircleCheck },
  inactive: { label: 'غير نشط', tone: 'neutral', icon: CircleMinus },
  accepted: { label: 'مقبول', tone: 'success', icon: CircleCheck },
  revoked: { label: 'ملغي الصلاحية', tone: 'danger', icon: CircleX },
  retired: { label: 'متقاعد', tone: 'neutral', icon: CircleMinus },
  suspended: { label: 'موقوف', tone: 'warning', icon: CircleMinus },
  notice_period: { label: 'فترة إخطار', tone: 'warning', icon: Clock3 },
  terminated: { label: 'منتهي', tone: 'danger', icon: CircleX },
  archived: { label: 'مؤرشف', tone: 'neutral', icon: CircleMinus },
  not_entered: { label: 'لم يدخل', tone: 'warning', icon: Clock3 },
  device_not_ready: { label: 'جهاز غير جاهز', tone: 'warning', icon: AlertTriangle },
  probation_failed: { label: 'لم يجتز التجربة', tone: 'danger', icon: CircleX },
  pending: { label: 'قيد المراجعة', tone: 'warning', icon: Clock3 },
  approved: { label: 'معتمد', tone: 'success', icon: CircleCheck },
  rejected: { label: 'مرفوض', tone: 'danger', icon: CircleX },
  cancelled: { label: 'ملغي', tone: 'neutral', icon: CircleMinus },
  withdrawn: { label: 'مسحوب', tone: 'neutral', icon: CircleMinus },
  expired: { label: 'منتهي الصلاحية', tone: 'danger', icon: Clock3 },
  self: { label: 'تقييم ذاتي', tone: 'info', icon: Clock3 },
  manager: { label: 'عند المدير', tone: 'violet', icon: Clock3 },
  secretary: { label: 'عند السكرتير', tone: 'info', icon: Clock3 },
  executive: { label: 'مراجعة تنفيذية', tone: 'warning', icon: AlertTriangle },
  finalized: { label: 'مكتمل', tone: 'success', icon: CircleCheck },
  announcement: { label: 'إعلان', tone: 'info', icon: Megaphone },
  decision: { label: 'قرار', tone: 'violet', icon: FileText },
  alert: { label: 'تنبيه', tone: 'warning', icon: AlertTriangle },
  poll: { label: 'تصويت', tone: 'info', icon: FileText },
  meeting: { label: 'اجتماع', tone: 'violet', icon: Clock3 },
  holiday_notice: { label: 'إشعار عطلة', tone: 'info', icon: Megaphone },
  kpi_notice: { label: 'إشعار أداء', tone: 'violet', icon: FileText },
  attendance_notice: { label: 'إشعار حضور', tone: 'info', icon: Clock3 },
  request: { label: 'طلب', tone: 'info', icon: FileText },
  kpi: { label: 'KPI', tone: 'violet', icon: FileText },
  report: { label: 'تقرير', tone: 'neutral', icon: FileText },
  case: { label: 'قضية', tone: 'danger', icon: AlertTriangle },
  task: { label: 'مهمة', tone: 'info', icon: Clock3 },
  policy: { label: 'سياسة', tone: 'violet', icon: FileText },
  low: { label: 'منخفضة', tone: 'neutral', icon: CircleMinus },
  normal: { label: 'عادية', tone: 'info', icon: CircleMinus },
  high: { label: 'مرتفعة', tone: 'warning', icon: AlertTriangle },
  urgent: { label: 'عاجلة', tone: 'danger', icon: AlertTriangle },
  published: { label: 'منشور', tone: 'success', icon: CircleCheck },
  in_review: { label: 'قيد المراجعة', tone: 'warning', icon: Clock3 },
  submitted: { label: 'جديد', tone: 'info', icon: Clock3 },
  needs_more_information: { label: 'تحتاج استكمالًا', tone: 'warning', icon: Clock3 },
  under_review: { label: 'قيد المراجعة', tone: 'info', icon: Clock3 },
  waiting_for_respondent: { label: 'بانتظار إفادة الطرف', tone: 'warning', icon: Clock3 },
  waiting_for_witness: { label: 'بانتظار شاهد', tone: 'warning', icon: Clock3 },
  session_scheduled: { label: 'جلسة محددة', tone: 'violet', icon: Clock3 },
  session_completed: { label: 'جلسة منعقدة', tone: 'success', icon: CircleCheck },
  committee_deliberation: { label: 'قيد المداولة', tone: 'violet', icon: Clock3 },
  settlement_pending: { label: 'بانتظار التسوية', tone: 'warning', icon: Clock3 },
  escalated_to_executive: { label: 'مصعدة للمدير التنفيذي', tone: 'danger', icon: AlertTriangle },
  returned_to_committee: { label: 'معادة إلى اللجنة', tone: 'warning', icon: Clock3 },
  decision_issued: { label: 'صدر القرار', tone: 'success', icon: FileText },
  reopened: { label: 'أعيد فتحها', tone: 'info', icon: Clock3 },
  cancelled_by_employee: { label: 'ألغاها الموظف', tone: 'neutral', icon: CircleMinus },
  assigned: { label: 'تم الإسناد', tone: 'violet', icon: Clock3 },
  in_progress: { label: 'قيد التنفيذ', tone: 'info', icon: Clock3 },
  waiting_requester: { label: 'بانتظار صاحب الطلب', tone: 'warning', icon: Clock3 },
  resolved: { label: 'تم الحل', tone: 'success', icon: CircleCheck },
  resolved_friendly: { label: 'حل ودي', tone: 'success', icon: CircleCheck },
  closed: { label: 'مغلق', tone: 'neutral', icon: CircleMinus },
  done: { label: 'مكتملة', tone: 'success', icon: CircleCheck },
  medium: { label: 'متوسطة', tone: 'info', icon: CircleMinus },
  critical: { label: 'حرجة', tone: 'danger', icon: AlertTriangle },
  fresh: { label: 'متصل', tone: 'success', icon: CircleCheck },
  stale: { label: 'إشارة قديمة', tone: 'warning', icon: Clock3 },
  no_signal: { label: 'دون إشارة', tone: 'danger', icon: CircleX },
  overdue: { label: 'متجاوز SLA', tone: 'danger', icon: AlertTriangle },
  trusted: { label: 'موثوق', tone: 'success', icon: CircleCheck },
  untrusted: { label: 'غير موثوق', tone: 'warning', icon: AlertTriangle },
  success: { label: 'ناجح', tone: 'success', icon: CircleCheck },
  succeeded: { label: 'ناجح', tone: 'success', icon: CircleCheck },
  failed: { label: 'فشل', tone: 'danger', icon: CircleX },
  error: { label: 'خطأ', tone: 'danger', icon: CircleX },
  retrying: { label: 'إعادة محاولة', tone: 'warning', icon: Clock3 },
  processing: { label: 'قيد المعالجة', tone: 'info', icon: Clock3 },
  delivered: { label: 'تم التسليم', tone: 'success', icon: CircleCheck },
  dead_letter: { label: 'فشل نهائي', tone: 'danger', icon: CircleX },
  allowed: { label: 'مسموح', tone: 'success', icon: CircleCheck },
  replaced: { label: 'مستبدل', tone: 'neutral', icon: CircleMinus },
  auto_revoked: { label: 'إلغاء تلقائي', tone: 'warning', icon: AlertTriangle },
  blocked: { label: 'محظور', tone: 'danger', icon: CircleX },
  detected: { label: 'مكتشف', tone: 'warning', icon: AlertTriangle },
  info: { label: 'معلومات', tone: 'info', icon: CircleMinus },
  notice: { label: 'تنبيه', tone: 'info', icon: Clock3 },
  warning: { label: 'تحذير', tone: 'warning', icon: AlertTriangle },
  inbound: { label: 'وارد', tone: 'violet', icon: Clock3 },
  outbound: { label: 'صادر', tone: 'info', icon: Clock3 },
};

export function StatusBadge({ status, value, label }: { status?: string; value?: string; label?: string }) {
  const key = value ?? status ?? 'unknown';
  const meta = map[key] ?? { label: key, tone: 'neutral' as const, icon: CircleMinus };
  const Icon = meta.icon;
  return <span className={`status-badge status-${meta.tone}`}><Icon className="size-3.5" aria-hidden="true" />{label ?? meta.label}</span>;
}
