import { Archive, BadgeCheck, BriefcaseBusiness, FileWarning, Laptop, LogOut, PackageCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { EmptyState } from '../../ui/EmptyState';
import { ErrorState } from '../../ui/ErrorState';
import { MetricCard } from '../../ui/MetricCard';
import { PageHeader } from '../../ui/PageHeader';
import { MetricSkeletonRow } from '../../ui/Skeletons';
import { StatusBadge } from '../../ui/StatusBadge';
import { UserAvatar } from '../../ui/UserAvatar';
import { useOrganizationAdminCatalog } from '../management/useAdminOperations';
import { useLifecycleCommands, useLifecycleOperations } from './useAdvancedOperations';

export function LifecycleOperationsPage() {
  const query = useLifecycleOperations();
  const org = useOrganizationAdminCatalog();
  const commands = useLifecycleCommands();
  const employees = org.data?.employees ?? [];
  const data = query.data;
  const [asset, setAsset] = useState({ code: '', type: 'device', name: '', serial: '', condition: 'جيدة', location: '' });
  const [assignment, setAssignment] = useState({ assetId: '', employeeId: '' });
  const [offboarding, setOffboarding] = useState({ employeeId: '', reasonType: 'resignation', reason: '', noticeDate: '', lastWorkingDate: '', handoverEmployeeId: '' });
  const openCases = useMemo(() => data?.offboarding.filter((item) => !['completed', 'cancelled'].includes(item.status)) ?? [], [data]);
  const expiringDocs = useMemo(() => data?.documents.filter((item) => item.expiryDate && new Date(item.expiryDate).getTime() <= Date.now() + 30 * 86400000) ?? [], [data]);

  if (query.isLoading && !data) {
    return <div className="space-y-6">
      <PageHeader title="المستندات والعهد وOffboarding" description="تشغيل دورة الوثائق والعهد وإخلاء الطرف وإنهاء الخدمة من شاشة واحدة، مع منع الإنهاء قبل اكتمال المتطلبات." />
      <MetricSkeletonRow count={3} />
    </div>;
  }

  if (query.isError && !data) {
    return <div className="space-y-6">
      <PageHeader title="المستندات والعهد وOffboarding" description="تشغيل دورة الوثائق والعهد وإخلاء الطرف وإنهاء الخدمة من شاشة واحدة، مع منع الإنهاء قبل اكتمال المتطلبات." />
      <ErrorState description={query.error instanceof Error ? query.error.message : undefined} onRetry={() => void query.refetch()} />
    </div>;
  }

  return <div className="space-y-6">
    <PageHeader title="المستندات والعهد وOffboarding" description="تشغيل دورة الوثائق والعهد وإخلاء الطرف وإنهاء الخدمة من شاشة واحدة، مع منع الإنهاء قبل اكتمال المتطلبات." />
    {data ? <section className="grid gap-6 sm:grid-cols-3"><MetricCard label="مستندات تنتهي خلال 30 يومًا" value={data.expiringDocuments} icon={FileWarning} /><MetricCard label="عهد مسندة" value={data.assignedAssets} icon={Laptop} /><MetricCard label="حالات إخلاء مفتوحة" value={data.openOffboarding} icon={LogOut} /></section> : null}

    <section className="grid gap-6 xl:grid-cols-2">
      <form className="card space-y-3 p-5" onSubmit={(e) => { e.preventDefault(); void commands.saveAsset.mutateAsync({ p_asset_id: null, p_asset_code: asset.code, p_asset_type: asset.type, p_name: asset.name, p_serial: asset.serial || null, p_condition: asset.condition || null, p_location: asset.location || null, p_notes: null }).then(() => setAsset({ code: '', type: 'device', name: '', serial: '', condition: 'جيدة', location: '' })); }}><h2 className="text-lg font-black">إضافة عهدة للمخزون</h2><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><input className="input" aria-label="كود العهدة" placeholder="كود العهدة" value={asset.code} onChange={(e) => setAsset({ ...asset, code: e.target.value })} /><input className="input" aria-label="اسم العهدة" placeholder="اسم العهدة" value={asset.name} onChange={(e) => setAsset({ ...asset, name: e.target.value })} required /></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><select className="input" aria-label="نوع العهدة" value={asset.type} onChange={(e) => setAsset({ ...asset, type: e.target.value })}><option value="device">جهاز</option><option value="phone">هاتف</option><option value="sim">شريحة</option><option value="key">مفتاح</option><option value="uniform">زي</option><option value="other">أخرى</option></select><input className="input" aria-label="الرقم التسلسلي" placeholder="الرقم التسلسلي" value={asset.serial} onChange={(e) => setAsset({ ...asset, serial: e.target.value })} /></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><input className="input" aria-label="الحالة" placeholder="الحالة" value={asset.condition} onChange={(e) => setAsset({ ...asset, condition: e.target.value })} /><input className="input" aria-label="الموقع الحالي" placeholder="الموقع الحالي" value={asset.location} onChange={(e) => setAsset({ ...asset, location: e.target.value })} /></div><button className="btn-primary w-full" disabled={commands.saveAsset.isPending}><PackageCheck className="size-4" aria-hidden="true" />إضافة للمخزون</button></form>

      <form className="card space-y-3 p-5" onSubmit={(e) => { e.preventDefault(); void commands.assignAsset.mutateAsync({ p_asset_id: assignment.assetId, p_employee_id: assignment.employeeId, p_condition: null, p_receipt_path: null, p_notes: null }).then(() => setAssignment({ assetId: '', employeeId: '' })); }}><h2 className="text-lg font-black">تسليم عهدة</h2><select className="input" aria-label="اختر عهدة متاحة" value={assignment.assetId} onChange={(e) => setAssignment({ ...assignment, assetId: e.target.value })} required><option value="">اختر عهدة متاحة</option>{data?.assets.filter((item) => item.status === 'available').map((item) => <option value={item.id} key={item.id}>{item.name} {item.assetCode ? `— ${item.assetCode}` : ''}</option>)}</select><select className="input" aria-label="الموظف" value={assignment.employeeId} onChange={(e) => setAssignment({ ...assignment, employeeId: e.target.value })} required><option value="">اختر الموظف</option>{employees.filter((item) => item.active).map((employee) => <option value={employee.id} key={employee.id}>{employee.name} — {employee.code}</option>)}</select><button className="btn-primary w-full" disabled={commands.assignAsset.isPending}><BriefcaseBusiness className="size-4" aria-hidden="true" />تسليم العهدة</button></form>
    </section>

    <section className="grid gap-6 xl:grid-cols-[1fr_420px]">
      <div className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-black">المستندات القريبة من الانتهاء</h2><span className="muted text-sm">{expiringDocs.length} مستند</span></div>{expiringDocs.length === 0 ? <div className="mt-4"><EmptyState title="لا توجد مستندات قريبة من الانتهاء" description="ستظهر هنا الوثائق التي تحتاج تجديدًا خلال 30 يومًا." /></div> : <div className="mt-4 space-y-3">{expiringDocs.map((item) => <article key={item.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><UserAvatar displayName={item.employeeName} size="sm" /><strong>{item.employeeName}</strong><p className="muted text-sm">{item.title ?? item.type} · ينتهي {item.expiryDate}</p></div><div className="flex gap-2"><StatusBadge value={item.status} />{!item.verified ? <button className="btn-primary" onClick={() => void commands.reviewDocument.mutateAsync({ p_document_id: item.id, p_decision: 'verified', p_reason: null })}><BadgeCheck className="size-4" aria-hidden="true" />تحقق</button> : null}<button className="btn-secondary" onClick={() => { const reason = window.prompt('سبب الرفض'); if (reason) void commands.reviewDocument.mutateAsync({ p_document_id: item.id, p_decision: 'rejected', p_reason: reason }); }}>رفض</button></div></div></article>)}</div>}</div>

      <form className="card space-y-3 p-5" onSubmit={(e) => { e.preventDefault(); void commands.startOffboarding.mutateAsync({ p_employee_id: offboarding.employeeId, p_reason_type: offboarding.reasonType, p_reason: offboarding.reason || null, p_notice_date: offboarding.noticeDate || null, p_last_working_date: offboarding.lastWorkingDate, p_handover_employee_id: offboarding.handoverEmployeeId || null, p_clearance_items: null }).then(() => setOffboarding({ employeeId: '', reasonType: 'resignation', reason: '', noticeDate: '', lastWorkingDate: '', handoverEmployeeId: '' })); }}><h2 className="text-lg font-black">بدء Offboarding</h2><select className="input" aria-label="الموظف" value={offboarding.employeeId} onChange={(e) => setOffboarding({ ...offboarding, employeeId: e.target.value })} required><option value="">الموظف</option>{employees.filter((item) => item.active).map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select><select className="input" aria-label="سبب الإنهاء" value={offboarding.reasonType} onChange={(e) => setOffboarding({ ...offboarding, reasonType: e.target.value })}><option value="resignation">استقالة</option><option value="termination">إنهاء</option><option value="contract_end">انتهاء عقد</option><option value="retirement">تقاعد</option><option value="probation_failed">عدم اجتياز التجربة</option><option value="other">أخرى</option></select><textarea className="input min-h-20" aria-label="السبب والتفاصيل" placeholder="السبب والتفاصيل" value={offboarding.reason} onChange={(e) => setOffboarding({ ...offboarding, reason: e.target.value })} /><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-bold">تاريخ الإخطار<input type="date" className="input mt-1" value={offboarding.noticeDate} onChange={(e) => setOffboarding({ ...offboarding, noticeDate: e.target.value })} /></label><label className="text-xs font-bold">آخر يوم عمل<input type="date" className="input mt-1" value={offboarding.lastWorkingDate} onChange={(e) => setOffboarding({ ...offboarding, lastWorkingDate: e.target.value })} required /></label></div><select className="input" aria-label="موظف استلام وتسليم المعرفة" value={offboarding.handoverEmployeeId} onChange={(e) => setOffboarding({ ...offboarding, handoverEmployeeId: e.target.value })}><option value="">موظف استلام وتسليم المعرفة</option>{employees.filter((item) => item.active && item.id !== offboarding.employeeId).map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select><button className="btn-primary w-full" disabled={commands.startOffboarding.isPending}><LogOut className="size-4" aria-hidden="true" />بدء إخلاء الطرف</button></form>
    </section>

    <section className="card p-5"><h2 className="text-lg font-black">حالات إخلاء الطرف</h2>{openCases.length === 0 ? <EmptyState title="لا توجد حالات مفتوحة" description="لا توجد عمليات Offboarding جارية." /> : <div className="mt-4 space-y-4">{openCases.map((item) => <article key={item.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><UserAvatar displayName={item.employeeName} size="sm" /><strong>{item.employeeName}</strong><p className="muted text-sm">{item.caseNumber} · آخر يوم {item.lastWorkingDate}</p></div><StatusBadge value={item.status} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{item.clearance.map((clearance) => <div key={clearance.id} className="rounded-xl bg-[var(--surface-muted)] p-3"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{clearance.title}</strong><p className="muted text-xs">{clearance.category}</p></div><StatusBadge value={clearance.status} /></div>{!['completed', 'waived'].includes(clearance.status) ? <div className="mt-3 flex gap-2"><button className="btn-primary flex-1 text-xs" onClick={() => void commands.transitionClearance.mutateAsync({ p_item_id: clearance.id, p_status: 'completed', p_note: 'تمت المراجعة', p_evidence_path: null })}>إكمال</button><button className="btn-secondary flex-1 text-xs" onClick={() => { const reason = window.prompt('سبب الإعفاء'); if (reason) void commands.transitionClearance.mutateAsync({ p_item_id: clearance.id, p_status: 'waived', p_note: reason, p_evidence_path: null }); }}>إعفاء</button></div> : null}</div>)}</div>{item.status === 'ready_for_approval' ? <button className="btn-primary mt-4" onClick={() => void commands.approveOffboarding.mutateAsync({ p_case_id: item.id, p_final_settlement_reference: null, p_exit_interview_notes: null })}><Archive className="size-4" aria-hidden="true" />الاعتماد النهائي وإنهاء الخدمة</button> : null}</article>)}</div>}</section>
  </div>;
}
