import { z } from 'zod';

const uuid = z.string().uuid();

export const publicReleasePolicySchema = z.object({
  action: z.enum(['none', 'update_available', 'update_required', 'maintenance', 'blocked']),
  platform: z.enum(['android', 'ios', 'web']),
  environment: z.enum(['development', 'staging', 'production']),
  currentVersion: z.string(),
  currentBuild: z.number().int().nonnegative(),
  latestVersion: z.string(),
  latestBuild: z.number().int().nonnegative(),
  minSupportedVersion: z.string(),
  minSupportedBuild: z.number().int().nonnegative(),
  forceUpdate: z.boolean(),
  maintenance: z.boolean(),
  messageAr: z.string().nullable(),
  storeUrl: z.string().nullable(),
  checkedAt: z.string(),
});
export type PublicReleasePolicy = z.infer<typeof publicReleasePolicySchema>;

export const releaseGovernanceCatalogSchema = z.object({
  policies: z.array(z.object({
    id: uuid,
    platform: z.enum(['android', 'ios', 'web']),
    environment: z.enum(['development', 'staging', 'production']),
    latestVersion: z.string(),
    latestBuild: z.number().int().nonnegative(),
    minSupportedVersion: z.string(),
    minSupportedBuild: z.number().int().nonnegative(),
    forceUpdate: z.boolean(),
    maintenance: z.boolean(),
    maintenanceMessageAr: z.string().nullable(),
    updateMessageAr: z.string().nullable(),
    storeUrl: z.string().nullable(),
    rolloutPercent: z.number().min(0).max(100),
    updatedAt: z.string(),
  })),
  devices: z.array(z.object({
    id: uuid,
    installationId: z.string(),
    userId: uuid.nullable(),
    employeeId: uuid.nullable(),
    employeeName: z.string().nullable(),
    employeeCode: z.string().nullable(),
    platform: z.enum(['android', 'ios', 'web']),
    deviceName: z.string().nullable(),
    deviceModel: z.string().nullable(),
    osVersion: z.string().nullable(),
    appVersion: z.string(),
    appBuild: z.number().int().nonnegative(),
    environment: z.enum(['development', 'staging', 'production']),
    trusted: z.boolean(),
    status: z.enum(['active', 'revoked', 'blocked', 'retired']),
    lastSeenAt: z.string(),
  })),
  accessReviews: z.array(z.object({
    id: uuid,
    name: z.string(),
    status: z.enum(['draft', 'active', 'completed', 'cancelled']),
    startsAt: z.string().nullable(),
    dueAt: z.string().nullable(),
    totalItems: z.number(),
    pendingItems: z.number(),
    revokedItems: z.number(),
  })),
  reviewItems: z.array(z.object({
    id: uuid,
    campaignId: uuid,
    userRoleId: uuid,
    userId: uuid,
    roleId: uuid,
    employeeName: z.string().nullable(),
    employeeCode: z.string().nullable(),
    roleName: z.string(),
    decision: z.enum(['pending', 'keep', 'revoke', 'change_scope', 'expired']),
    decisionReason: z.string().nullable(),
    decidedAt: z.string().nullable(),
    snapshot: z.unknown(),
  })),
  breakGlass: z.array(z.object({
    id: uuid,
    targetUserId: uuid,
    targetName: z.string().nullable(),
    targetCode: z.string().nullable(),
    roleId: uuid,
    roleName: z.string(),
    durationMinutes: z.number().int(),
    reason: z.string(),
    status: z.enum(['pending', 'approved', 'rejected', 'expired', 'revoked']),
    requestedBy: uuid,
    requestedAt: z.string(),
    activeUntil: z.string().nullable(),
  })),
  privacyRequests: z.array(z.object({
    id: uuid,
    requestNumber: z.number(),
    requesterUserId: uuid,
    employeeName: z.string().nullable(),
    employeeCode: z.string().nullable(),
    requestType: z.enum(['access', 'correction', 'export', 'restriction', 'deletion', 'objection']),
    details: z.string(),
    status: z.enum(['submitted', 'in_review', 'waiting_requester', 'approved', 'rejected', 'completed', 'cancelled']),
    dueAt: z.string().nullable(),
    decisionReason: z.string().nullable(),
    createdAt: z.string(),
  })),
  outbox: z.object({
    pending: z.number(),
    failed: z.number(),
    delivered: z.number(),
    oldestPendingAt: z.string().nullable(),
  }),
  roles: z.array(z.object({ id: uuid, slug: z.string(), name: z.string(), fullAccess: z.boolean() })),
  users: z.array(z.object({ userId: uuid, employeeId: uuid.nullable(), name: z.string().nullable(), employeeCode: z.string().nullable(), status: z.string() })),
  lastUpdatedAt: z.string(),
});
export type ReleaseGovernanceCatalog = z.infer<typeof releaseGovernanceCatalogSchema>;
