import { AlertCircle, ArrowLeft, Clock3, Inbox } from 'lucide-react';
import { Link } from 'react-router-dom';
import { EmptyState } from '../../ui/EmptyState';
import { ErrorState } from '../../ui/ErrorState';
import { MetricCard } from '../../ui/MetricCard';
import { PageHeader } from '../../ui/PageHeader';
import { MetricSkeletonRow, ListSkeleton } from '../../ui/Skeletons';
import { StatusBadge } from '../../ui/StatusBadge';
import { useActionCenter } from './useActionCenter';
export function ActionCenterPage() { const query = useActionCenter(); const items = query.data ?? []; const isInitialLoading = query.isLoading && items.length === 0; return <div className="space-y-6"><PageHeader eyebrow="مركز الإجراءات" title="مركز الإجراءات الموحد" description="كل عنصر ينتظر منك قرارًا أو مراجعة أو متابعة في قائمة واحدة مرتبة حسب الأولوية والمهلة." />{isInitialLoading ? <MetricSkeletonRow count={3} /> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="إجمالي العناصر" value={items.length} icon={Inbox} /><MetricCard label="عاجل" value={items.filter((x) => x.priority === 'urgent').length} icon={AlertCircle} /><MetricCard label="مرتفع" value={items.filter((x) => x.priority === 'high').length} icon={Clock3} /></section>}{query.isError ? <ErrorState title="تعذر تحميل مركز الإجراءات" description={query.error instanceof Error ? query.error.message : undefined} onRetry={() => void query.refetch()} /> : isInitialLoading ? <ListSkeleton rows={3} label="جارٍ تحميل الإجراءات" /> : items.length === 0 ? <EmptyState title="لا توجد إجراءات معلقة" description="لا توجد عناصر تحتاج تدخلك حاليًا." /> : <section className="space-y-3">{items.map((item) => <article key={item.id} className="card flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={item.kind} /><StatusBadge value={item.priority} /><StatusBadge value={item.status} /></div><h2 className="mt-3 font-black">{item.title}</h2>{item.subtitle ? <p className="muted mt-1 text-sm">{item.subtitle}</p> : null}{item.dueAt ? <p className="mt-2 text-xs font-bold text-[var(--warning)]">المهلة: {new Intl.DateTimeFormat('ar-EG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.dueAt))}</p> : null}</div><Link className="btn-primary shrink-0" to={item.actionUrl}>فتح الإجراء<ArrowLeft className="size-4" aria-hidden="true" /></Link></article>)}</section>}</div>; }
