-- سحب صلاحية EXECUTE من anon على كل الدوال التطبيقية
-- يستثنى: دوال الامتدادات (citext, pgcrypto, pg_trgm, etc.)
-- يُعاد منح: handle_new_user, activate_employee_after_first_login, get_public_release_policy
-- هذا إصلاح أمني حرج — يمنع المستخدمين غير المصادقين من الوصول للدوال الحساسة

BEGIN;

REVOKE EXECUTE ON FUNCTION public._build_attendance_statement(p_employee_id uuid, p_year integer, p_month integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public._on_primary_department_removed() FROM anon;
REVOKE EXECUTE ON FUNCTION public._sync_primary_department() FROM anon;
REVOKE EXECUTE ON FUNCTION public.accept_dispute_case(p_case_id uuid, p_assigned_to uuid, p_quorum integer, p_due_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_announcement(p_announcement_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_assignment(p_assignment_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_decision(p_decision_id uuid, p_acknowledge boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_decision(p_decision_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_dispute_decision(p_decision_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_kpi_evaluation(p_evaluation_id uuid, p_note text, p_appeal_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acknowledge_policy(p_policy_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.add_kpi_evidence(p_evaluation_id uuid, p_criterion_id uuid, p_type text, p_title text, p_description text, p_storage_path text, p_external_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.adjust_leave_balance(p_employee_id uuid, p_leave_type_id uuid, p_year integer, p_units numeric, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.advance_application_stage(p_application_id uuid, p_to_stage_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.advance_kpi_stage(p_evaluation_id uuid, p_action text, p_scores jsonb, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_break_glass(p_request_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_offboarding_case(p_case_id uuid, p_final_settlement_reference text, p_exit_interview_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.assign_asset_admin(p_asset_id uuid, p_employee_id uuid, p_condition text, p_receipt_path text, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.assign_employee_department(p_employee_id uuid, p_department_id uuid, p_job_title text, p_is_primary boolean, p_note text, p_allocation_percentage integer, p_start_date date, p_end_date date, p_functional_manager_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_row_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_late_minutes(p_event_at timestamp with time zone, p_shift_start time without time zone, p_grace_minutes integer, p_reference_date date, p_timezone text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_late_minutes(p_event_at timestamp with time zone, p_shift_start time without time zone, p_grace_minutes integer, p_reference_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_dispute(p_case_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_employee(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_access_employee(p_employee_id uuid, p_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_assignment_type(p_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_assignment_type_org_wide(p_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_view_live_location_video(p_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_location_request_as_requester(p_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_my_dispute(p_case_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_request(p_request_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_work_assignment(p_assignment_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cast_decision_vote(p_poll_id uuid, p_option_ids uuid[], p_rating numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_attendance_punch_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_device_register_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_employee_create_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_location_request_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_post_publish_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit(p_domain text, p_max_count integer, p_window_minutes integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_role_assign_rate_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.close_attendance_period(p_month date, p_legal_entity_id uuid, p_branch_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.close_kpi_cycle(p_cycle_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_dispute_action(p_action_id uuid, p_proof text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_live_location_response(p_request_id uuid, p_latitude double precision, p_longitude double precision, p_accuracy numeric, p_address text, p_captured_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_access_review_campaign(p_name text, p_description text, p_due_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_decision_draft(p_title text, p_body text, p_category text, p_effective_date date, p_requires_read_receipt boolean, p_expected_outcome text, p_success_metric text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_job_requisition_admin(p_department_id uuid, p_title text, p_headcount integer, p_reason text, p_budget_range text, p_submit boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_kpi_cycle_admin(p_month date, p_template_id uuid, p_self_due timestamp with time zone, p_manager_due timestamp with time zone, p_secretary_due timestamp with time zone, p_executive_due timestamp with time zone, p_open_now boolean, p_use_parallel_flow boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_kpi_cycle_admin(p_month date, p_template_id uuid, p_self_due timestamp with time zone, p_manager_due timestamp with time zone, p_secretary_due timestamp with time zone, p_executive_due timestamp with time zone, p_open_now boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_kpi_policy_version(p_name text, p_attendance_rules jsonb, p_rating_bands jsonb, p_allow_target_overachievement boolean, p_effective_from date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_my_dispute(p_title text, p_description text, p_case_type text, p_respondent_employee_id uuid, p_severity text, p_confidential boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_onboarding_journey_admin(p_employee_id uuid, p_started_at timestamp with time zone, p_probation_end date, p_tasks jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_team_task(p_employee_id uuid, p_title text, p_description text, p_priority text, p_due_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_work_assignment(p_assignment_type text, p_title text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_participant_ids uuid[], p_description text, p_location text, p_responsible_employee_id uuid, p_needs_report boolean, p_report_due_at timestamp with time zone, p_payload jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_employee_id() FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_employee_scope() FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_is_full_access() FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_is_hr_only() FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_is_super_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.current_role_ids() FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_access_review_item(p_item_id uuid, p_decision text, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_attendance_correction(p_id uuid, p_decision text, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_dispute_appeal(p_appeal_id uuid, p_decision text, p_resolution text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_kpi_appeal(p_appeal_id uuid, p_decision text, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_overtime_record(p_id uuid, p_decision text, p_approved_minutes integer, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_privacy_request(p_request_id uuid, p_status text, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_request(p_request_id uuid, p_decision text, p_comment text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decide_work_assignment(p_assignment_id uuid, p_decision text, p_comment text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.decision_content_hash(p_title text, p_body text, p_version integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.declare_dispute_conflict(p_case_id uuid, p_has_conflict boolean, p_details text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.effective_annual_entitlement(p_employee_id uuid, p_as_of date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.employee_has_role(p_employee_id uuid, p_role_slug text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enqueue_dispute_notification(p_case_id uuid, p_recipient_employee_id uuid, p_event_key text, p_title text, p_body text, p_priority text, p_action_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_leave_account(p_employee_id uuid, p_leave_type_id uuid, p_year integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.escape_ilike(p_input text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.extend_request_deadline(p_request_id uuid, p_hours integer, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.finalize_dispute_session(p_session_id uuid, p_minutes text, p_attendance jsonb, p_outcome text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.finalize_dispute_session_v2(p_session_id uuid, p_minutes text, p_attendance jsonb, p_outcome text, p_minutes_data jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.first_active_employee_for_role(p_role_slug text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.geo_distance_meters(p_lat1 double precision, p_lon1 double precision, p_lat2 double precision, p_lon2 double precision) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_access_admin_catalog() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_access_overview() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_attendance_dashboard(p_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_attendance_operations_catalog(p_month date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_attendance_today_overview(p_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_committee_dispute_portal() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_overview(p_workspace text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dispute_case_recommendations(p_case_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dispute_operations_catalog(p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_dispute_participant_directory(p_search text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_documents_assets_offboarding_catalog(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_employee_360(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_employee_departments(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_employee_home() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_employee_monthly_attendance_statement(p_employee_id uuid, p_year integer, p_month integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_escalation_hours(p_manager_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_executive_attendance_overview(p_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_executive_dispute_inbox() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_hr_reports_summary() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_kpi_admin_catalog(p_month date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_kpi_cycle_report(p_cycle_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_kpi_evaluation_form(p_evaluation_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_kpi_validation_errors(p_evaluation_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_live_location_response(p_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_location_directory(p_search text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_action_target(p_action_id text, p_kind text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_daily_reports(p_employee_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_executive_command_center() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_executive_employee_summary(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_executive_people(p_search text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_feed_item(p_kind text, p_item_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_manager_operations(p_from date, p_to date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mobile_org_chart() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_attendance_history(p_limit integer, p_before timestamp with time zone, p_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_attendance_services(p_from date, p_to date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_dispute_portal() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_leave_balances(p_year integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_live_location_requests(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_mobile_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_mobile_tasks(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_mobile_team(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_monthly_attendance_statement(p_year integer, p_month integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_notifications(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_official_feed_admin(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_onboarding_admin_catalog(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_org_chart(p_root uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_organization_admin_catalog() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_organization_overview() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_recruitment_overview() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_request_inbox(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_system_overview() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_system_setting_int(p_key text, p_default integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_system_setting_text(p_key text, p_default text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_work_assignments_inbox(p_scope text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_any_permission(p_codes text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_any_scoped_permission(p_permission_slugs text[], p_scope_type text, p_scope_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_permission(p_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_scoped_permission(p_permission_slug text, p_scope_type text, p_scope_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_management_descendant(p_manager_employee_id uuid, p_target_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.issue_dispute_decision(p_case_id uuid, p_session_id uuid, p_text text, p_rationale text, p_outcome text, p_owner_id uuid, p_due_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.kpi_effective_deadline(p_cycle kpi_cycles) FROM anon;
REVOKE EXECUTE ON FUNCTION public.kpi_effective_score(p_evaluation_id uuid, p_criterion_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.kpi_rating_for_score(p_policy_id uuid, p_score numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.kpi_total_score(p_evaluation_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.leave_request_units(p_leave_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_assignment_to_initiatives(p_assignment_id uuid, p_evaluation_id uuid, p_points numeric, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_fundraising_to_target(p_assignment_id uuid, p_evaluation_id uuid, p_weight numeric, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_audit_event(p_event_type text, p_category text, p_severity text, p_target_table text, p_target_id uuid, p_summary_ar text, p_description text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_audit_event(p_event_type text, p_target_table text, p_target_id uuid, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_security_event(p_event_type text, p_severity text, p_outcome text, p_identifier text, p_details jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.manage_kpi_cycle(p_cycle_id uuid, p_action text, p_reason text, p_extended_until timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_all_notifications_read() FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_my_notifications_read(p_ids uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_notification_read(p_notification_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.normalize_live_location_notification() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_employee(p_employee_id uuid, p_title text, p_body text, p_category text, p_priority text, p_entity_type text, p_entity_id uuid, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.open_annual_leave_entitlement(p_employee_id uuid, p_year integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.override_kpi_score(p_evaluation_id uuid, p_criterion_id uuid, p_score numeric, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.passkey_credentials_force_untrusted() FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_dispute_sla(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.publish_official_announcement(p_title text, p_body text, p_category text, p_priority text, p_requires_acknowledgement boolean, p_banner_url text, p_post_type text, p_poll_options jsonb, p_expires_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.publish_official_announcement(p_title text, p_body text, p_category text, p_priority text, p_requires_acknowledgement boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.publish_official_announcement(p_title text, p_body text, p_category text, p_priority text, p_requires_acknowledgement boolean, p_banner_url text, p_post_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.publish_roster_admin(p_name text, p_period_start date, p_period_end date, p_department_id uuid, p_team_id uuid, p_branch_id uuid, p_days jsonb, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reassign_request(p_request_id uuid, p_new_manager_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_dispute_settlement(p_case_id uuid, p_type text, p_from uuid, p_to uuid, p_text text, p_publication_place text, p_due_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.refresh_kpi_attendance_inputs(p_cycle_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_dispute_evidence(p_case_id uuid, p_title text, p_storage_path text, p_mime_type text, p_file_size_bytes bigint, p_visibility text, p_description text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_employee_document_admin(p_employee_id uuid, p_doc_type text, p_title text, p_storage_path text, p_doc_number text, p_issue_date date, p_expiry date, p_file_hash text, p_mime_type text, p_size_bytes bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.register_live_location_video(p_request_id uuid, p_storage_path text, p_duration_seconds integer, p_size_bytes bigint, p_mime_type text, p_latitude double precision, p_longitude double precision, p_accuracy double precision) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_break_glass(p_request_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.remove_employee_department(p_employee_id uuid, p_department_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_attendance_correction(p_work_date date, p_type text, p_reason text, p_check_in timestamp with time zone, p_check_out timestamp with time zone, p_status text, p_attachment_path text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_break_glass(p_target_user_id uuid, p_role_id uuid, p_duration_minutes integer, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.resolve_request_approver(p_employee_id uuid, p_as_of date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.respond_live_location_request(p_request_id uuid, p_accept boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.return_asset_admin(p_assignment_id uuid, p_condition text, p_return_sig_path text, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.return_kpi_stage(p_evaluation_id uuid, p_target_stage text, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.review_daily_report(p_report_id uuid, p_manager_comment text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.review_employee_document(p_document_id uuid, p_decision text, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.revoke_managed_device(p_device_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.revoke_my_passkey(p_credential_id uuid, p_reason text) FROM anon;
DO $$ BEGIN REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM anon; EXCEPTION WHEN undefined_function THEN NULL; END $$;
REVOKE EXECUTE ON FUNCTION public.rpc_assign_role(p_user_id uuid, p_role_id uuid, p_scope_override jsonb, p_effective_from timestamp with time zone, p_effective_to timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_revoke_role(p_user_id uuid, p_role_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_set_role_permissions(p_role_id uuid, p_items jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_upsert_role(p_id uuid, p_slug text, p_name_ar text, p_name_en text, p_description text, p_color text, p_icon text, p_is_full_access boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_asset_admin(p_asset_id uuid, p_asset_code text, p_asset_type text, p_name text, p_serial text, p_condition text, p_location text, p_notes text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_kpi_compliance_metric(p_evaluation_id uuid, p_metric text, p_required integer, p_actual integer, p_exempt integer, p_cancelled integer, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_kpi_goal(p_evaluation_id uuid, p_goal_id uuid, p_title text, p_description text, p_target_value numeric, p_achieved_value numeric, p_unit text, p_weight numeric, p_due_date date, p_evidence_source text, p_employee_note text, p_manager_note text, p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_kpi_review_session(p_evaluation_id uuid, p_session jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.save_shift_admin(p_shift_id uuid, p_code text, p_name text, p_start time without time zone, p_end time without time zone, p_break_minutes integer, p_grace_in integer, p_grace_out integer, p_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.schedule_dispute_session(p_case_id uuid, p_type text, p_scheduled_at timestamp with time zone, p_location text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.schedule_dispute_session_v2(p_case_id uuid, p_type text, p_scheduled_at timestamp with time zone, p_ends_at timestamp with time zone, p_location text, p_modality text, p_participants jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.server_now() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_dispute_committee(p_case_id uuid, p_members jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_employee_status(p_employee_id uuid, p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_live_location_legal_hold(p_video_id uuid, p_hold_until timestamp with time zone, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_live_video_retention() FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_primary_department(p_employee_id uuid, p_department_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.soft_delete_employee(p_employee_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.start_offboarding_case(p_employee_id uuid, p_reason_type text, p_reason text, p_notice_date date, p_last_working_date date, p_handover_employee_id uuid, p_clearance_items jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_assignment_report(p_assignment_id uuid, p_report text, p_outcome text, p_achieved_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_dispute_appeal(p_decision_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_dispute_statement(p_case_id uuid, p_statement_type text, p_statement_text text, p_visibility text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_kpi_appeal(p_evaluation_id uuid, p_reason text, p_requested_outcome text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_live_location_point(p_request_id uuid, p_latitude double precision, p_longitude double precision, p_accuracy double precision, p_altitude double precision, p_speed double precision, p_heading double precision, p_is_mock boolean, p_address_ar text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_my_dispute(p_title text, p_description text, p_case_type text, p_priority text, p_incident_at timestamp with time zone, p_incident_location text, p_parties jsonb, p_witnesses jsonb, p_direct_manager_contacted boolean, p_amicable_attempted boolean, p_amicable_result text, p_requested_action text, p_confidential boolean, p_truth_confirmed boolean, p_confidentiality_accepted boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_my_dispute_v23(p_title text, p_description text, p_case_type text, p_parties jsonb, p_witnesses jsonb, p_truth_confirmed boolean, p_confidentiality_accepted boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_my_request(p_request_type text, p_title text, p_reason text, p_payload jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_privacy_request(p_request_type text, p_details text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.submit_request(p_request_type text, p_workflow_definition_id uuid, p_manager_employee_id uuid, p_title text, p_reason text, p_payload jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_adjust_escalation_deadline() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_block_disabled_leave_types() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_calculate_kpi_goal_score() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_device_approval_notify() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_employees_protect_job_fields() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_geofence_audit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_guard_request_decision_v10() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_kpi_stage_history() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_leave_attendance_on_approval() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_leave_reserve_on_detail() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_leave_settle_on_request_decision() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_link_request_attachments() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_open_employee_leave_entitlement() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_profiles_protect_sensitive() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_security_events_force_handler() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_service_requests_guard_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_set_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.tg_validate_leave_request_v10() FROM anon;
REVOKE EXECUTE ON FUNCTION public.transition_decision(p_decision_id uuid, p_action text, p_reason text, p_scheduled_for timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.transition_dispute_case(p_case_id uuid, p_action text, p_reason text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.transition_my_task(p_task_id uuid, p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.transition_offboarding_clearance_item(p_item_id uuid, p_status text, p_note text, p_evidence_path text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.transition_onboarding_task_admin(p_task_id uuid, p_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_announcement_broadcast_notify() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_fn_device_pending_notify_admins() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_fn_employee_devices_auto_replace() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_fn_public_holiday_broadcast() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trg_fn_role_assignment_notify() FROM anon;
REVOKE EXECUTE ON FUNCTION public.unlock_attendance_period(p_period_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_release_policy(p_platform text, p_environment text, p_latest_version text, p_latest_build integer, p_min_supported_version text, p_min_supported_build integer, p_force_update boolean, p_maintenance_enabled boolean, p_maintenance_message_ar text, p_update_message_ar text, p_store_url text, p_rollout_percent integer, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_department_admin(p_id uuid, p_legal_entity_id uuid, p_branch_id uuid, p_parent_id uuid, p_manager_id uuid, p_code text, p_name text, p_name_en text, p_is_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_my_daily_report(p_report_date date, p_achievements text, p_blockers text, p_tomorrow_plan text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.upsert_position_admin(p_id uuid, p_department_id uuid, p_team_id uuid, p_job_title_id uuid, p_grade_id uuid, p_reports_to_id uuid, p_code text, p_name text, p_name_en text, p_headcount integer, p_is_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.withdraw_escalation(p_request_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_count(p_text text) FROM anon;

-- إعادة منح الدوال التي تحتاج وصول anon
GRANT EXECUTE ON FUNCTION public.activate_employee_after_first_login() TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_release_policy(p_platform text, p_environment text, p_current_version text, p_current_build integer, p_installation_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;

COMMIT;
