-- ============================================================
-- 0488: rebuild stored notifications from clean templates
-- Repairs 152 broken titles / 127 broken bodies across 3 entity_types
-- that were generated by functions with FFFD/dual-LATIN1 corruption.
-- Generators are now clean (0483+0487 deployed); this rebuilds stored rows.
-- ============================================================

-- Helper: clean time string from U+FFFD residue (e.g., "03:11 �?" -> "03:11 ص")
-- Uses metadata event + workDate to infer AM/PM if suffix lost.
create or replace function public._clean_notif_time(p_raw text, p_event text, p_work_date date)
returns text language sql immutable as $$
  select case
    when p_raw is null then null
    when p_raw !~ '\uFFFD' then p_raw
    else regexp_replace(p_raw, '\uFFFD.', '',
      case
        when p_event = 'attendance_check_in' then ' ص'
        else ' م'
      end
    )
  end;
$$;

-- ============================================================
-- 1) attendance_daily: 36 rows
-- Templates from tg_attendance_daily_notify_manager (now clean):
--   self:     title='تم تسجيل حضورك'/'تم تسجيل انصرافك', body='تم تسجيل حضورك الساعة {time}'/'تم تسجيل انصرافك الساعة {time}'
--   manager:  title='وصل {name} للعمل بالمجمع'/'خرج {name} من المجمع', body='{name} — دخل/انصرف الساعة {time}'
--   executive: same as manager
-- ============================================================
update public.notifications n
set
  title = case
    when (n.metadata->>'self')::boolean then
      case (n.metadata->>'event')
        when 'attendance_check_in' then 'تم تسجيل حضورك'
        when 'attendance_check_out' then 'تم تسجيل انصرافك'
        else 'تحديث حضور'
      end
    else
      case (n.metadata->>'event')
        when 'attendance_check_in' then format('وصل %s للعمل بالمجمع', coalesce(e.full_name_ar, 'موظف'))
        when 'attendance_check_out' then format('خرج %s من المجمع', coalesce(e.full_name_ar, 'موظف'))
        else 'تحديث حضور'
      end
  end,
  body = case
    when (n.metadata->>'self')::boolean then
      format(
        'تم تسجيل %s الساعة %s',
        case (n.metadata->>'event')
          when 'attendance_check_in' then 'حضورك'
          when 'attendance_check_out' then 'انصرافك'
          else 'حضور'
        end,
        public._clean_notif_time(n.metadata->>'time', n.metadata->>'event', (n.metadata->>'workDate')::date)
      )
    else
      format(
        '%s — %s الساعة %s',
        coalesce(e.full_name_ar, 'موظف'),
        case (n.metadata->>'event')
          when 'attendance_check_in' then 'دخل'
          when 'attendance_check_out' then 'انصرف'
          else 'حدث'
        end,
        public._clean_notif_time(n.metadata->>'time', n.metadata->>'event', (n.metadata->>'workDate')::date)
      )
  end
from public.employees e
where n.entity_type = 'attendance_daily'
  and e.id = (n.metadata->>'employeeId')::uuid
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- ============================================================
-- 2) punch_reminder: 51 rows
-- Templates from generate_punch_reminders (now clean):
--   before_in:  title='تذكير بالحضور',           body='اقترب وقت الحضور ({shift_start}). لا تنسَ تسجيل البصمة.'
--   before_out: title='تذكير بالانصراف',         body='اقترب وقت الانصراف ({shift_end}). لا تنسَ تسجيل بصمة الانصراف.'
--   late_in:    title='⚠️ تأخير في الحضور',       body='لم تُسجَّل بصمة حضورك حتى الآن. سجّل البصمة في أقرب وقت.'
-- ============================================================
update public.notifications n
set
  title = case (n.metadata->>'kind')
    when 'before_in'  then 'تذكير بالحضور'
    when 'before_out' then 'تذكير بالانصراف'
    when 'late_in'    then '⚠️ تأخير في الحضور'
    else 'تذكير'
  end,
  body = case (n.metadata->>'kind')
    when 'before_in' then
      format(
        'اقترب وقت الحضور (%s). لا تنسَ تسجيل البصمة.',
        coalesce(
          (select to_char(s.start_time, 'hh12:mi') || case when extract(hour from s.start_time) < 12 then ' ص' else ' م' end from public.shifts s where s.id = (n.metadata->>'shiftId')::uuid),
          'غير محدد'
        )
      )
    when 'before_out' then
      format(
        'اقترب وقت الانصراف (%s). لا تنسَ تسجيل بصمة الانصراف.',
        coalesce(
          (select to_char(s.end_time, 'hh12:mi') || case when extract(hour from s.end_time) < 12 then ' ص' else ' م' end from public.shifts s where s.id = (n.metadata->>'shiftId')::uuid),
          'غير محدد'
        )
      )
    when 'late_in' then
      'لم تُسجَّل بصمة حضورك حتى الآن. سجّل البصمة في أقرب وقت.'
    else
      'تذكير بالبصمة'
  end
where n.entity_type = 'punch_reminder'
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- ============================================================
-- 3) request: 65 rows (multiple subtypes via metadata)
-- Rebuild from clean templates per escalation/kind
-- ============================================================

-- 3a) request_approval_needed (5 rows)
-- Template: title='طلب بانتظار مراجعة', body='{requestType_ar} — تحتاج قرار المدير'
update public.notifications n
set
  title = 'طلب بانتظار مراجعة',
  body = format(
    '%s — تحتاج قرار المدير',
    case (n.metadata->>'requestType')
      when 'mission' then 'مأمورية'
      when 'leave' then 'إجازة'
      when 'device' then 'جهاز'
      when 'access' then 'صلاحية'
      else 'طلب'
    end
  )
where n.entity_type = 'request'
  and (n.metadata->>'kind') = 'request_approval_needed'
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- 3b) operations-manager-1 escalation (approval needed by ops manager)
-- Template: title='طلب تصديق إضافي على طلبك في الدور التشغيلي 1', body='{camp/mission} — ثبت في حين ما زالت وردية مفتوحة'
update public.notifications n
set
  title = 'طلب تصديق إضافي على طلبك في الدور التشغيلي 1',
  body = format(
    '%s — ثبت في حين ما زالت وردية مفتوحة',
    case
      when n.body ~* 'كامب' then regexp_replace(n.body, '^.*?(كامب [^—]+).*$', '\1')
      when n.body ~* 'مأمورية' then 'مأمورية'
      else 'طلب'
    end
  )
where n.entity_type = 'request'
  and (n.metadata->>'escalation') = 'operations-manager-1'
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- 3c) executive_notify escalation (1 row)
update public.notifications n
set
  title = 'تصعيد طلب — متابعة',
  body = 'مأمورية'
where n.entity_type = 'request'
  and (n.metadata->>'escalation') = 'executive_notify'
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- 3d) final_reminder escalation (3+ rows)
-- Template: title='تذكير: طلب {type} تم إرساله منذ فترة', body='{camp/mission} — تحتاج قرار المدير (الأمر). الأمر المباشر قد وافق على طلب تصديق إضافي...'
update public.notifications n
set
  title = 'تذكير: طلب مأمورية تم إرساله منذ فترة',
  body = format(
    '%s — تحتاج قرار المدير (الأمر). الأمر المباشر قد وافق على طلب تصديق إضافي.',
    case
      when n.body ~* 'كامب' then regexp_replace(n.body, '^.*?(كامب [^—\n]+).*$', '\1')
      when n.body ~* 'مأمورية' then 'مأمورية'
      else 'طلب'
    end
  )
where n.entity_type = 'request'
  and (n.metadata->>'escalation') = 'final_reminder'
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- 3e) remaining request rows with kind=null (fallback: generic request template)
-- These appear to be various request status updates. Use a safe generic template.
update public.notifications n
set
  title = 'تحديث على طلبك',
  body = 'حدث تحديث على طلبك. راجع التفاصيل عبر الرابط.'
where n.entity_type = 'request'
  and (n.metadata->>'kind') is null
  and (n.metadata->>'escalation') is null
  and encode(convert_to(coalesce(n.title,''),'UTF8'),'hex') like '%efbfbd%';

-- Cleanup helper
drop function public._clean_notif_time(text, text, date);

-- Verification
do $$
declare
  v_broken_titles int;
  v_broken_bodies int;
begin
  select count(*) into v_broken_titles
  from public.notifications
  where encode(convert_to(coalesce(title,''),'UTF8'),'hex') like '%efbfbd%';
  select count(*) into v_broken_bodies
  from public.notifications
  where encode(convert_to(coalesce(body,''),'UTF8'),'hex') like '%efbfbd%';
  raise notice 'After repair: broken_titles=%, broken_bodies=%', v_broken_titles, v_broken_bodies;
  if v_broken_titles > 0 or v_broken_bodies > 0 then
    raise warning 'Some notifications still have U+FFFD - manual review needed';
  end if;
end $$;