$env:RELEASE_STORE_PASSWORD=$env:RELEASE_STORE_PASSWORD
$env:RELEASE_KEY_PASSWORD=$env:RELEASE_KEY_PASSWORD
$env:RELEASE_KEY_ALIAS=$env:RELEASE_KEY_ALIAS
$env:RELEASE_KEYSTORE_PATH=$env:RELEASE_KEYSTORE_PATH
flutter build apk --release